### ISSUE TITLE
代码中只映射了错误请求的结构体

### ISSUE THREAD

**Issue by feeops** [CatchZeng/feishu#2]
代码中只映射了错误请求的结构体

// Response response struct
type Response struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

如请求成功，返回体为：

{
	"Extra": null,
	"StatusCode": 0,
	"StatusMessage": "success"
}
如请求体格式错误，返回体如下。请检查：

请求体内容格式是否与各消息类型的示例代码一致
请求体大小不能超过20k
{
	"code": 9499,
	"msg": "Bad Request",
	"data": {}
}

参考文档
https://open.feishu.cn/document/ukTMukTMukTM/ucTM5YjL3ETO24yNxkjN#f62e72d5

**Comment by CatchZeng** [comment]
感谢你的指正，v1.3.2 已经加上了，可以查看最新的代码

**Comment by CatchZeng** [comment]
@feeops 如果没有问题，我这边就先关闭 issue 了，有问题的话再留言
