### ISSUE TITLE
Cannot import as package

### ISSUE THREAD

**Issue by tonyho** [CatchZeng/feishu#6]
I copied the example code from Readme.md, when compiling with go mod, it hints:

```
main.go:6:2: import "github.com/CatchZeng/feishu" is a program, not an importable package
```

The line 6 is the import sentence: 

```
import "github.com/CatchZeng/feishu"
```

How can I fix this?

**Comment by CatchZeng** [comment]
> I copied the example code from Readme.md, when compiling with go mod, it hints:
> 
> ```
> main.go:6:2: import "github.com/CatchZeng/feishu" is a program, not an importable package
> ```
> 
> The line 6 is the import sentence:
> 
> ```
> import "github.com/CatchZeng/feishu"
> ```
> 
> How can I fix this?

Sorry, I forgot to update the README before, now it has been updated, you can go to https://github.com/CatchZeng/feishu#%E4%BD%9C%E4%B8%BA-module to see how to use it.

```go
import "github.com/CatchZeng/feishu/pkg/feishu"
```

**Comment by tonyho** [comment]
> > I copied the example 
> >         code
> >          from Readme.md, when 
> >         compiling
> >          with go mod, it 
> >         hints
> >         :
> > ```
> > main.go:6:2: import "github.com/CatchZeng/feishu" is a program, not an importable package
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The line 6 is the 
> >         import
> >          sentence:
> > ```
> > import "github.com/CatchZeng/feishu"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How can I 
> >         fix
> >          this?
> 
> Sorry, I forgot to update the README before, now it has been updated, you can go to https://github.com/CatchZeng/feishu#%E4%BD%9C%E4%B8%BA-module to see how to use it.
> 
> ```go
> import "github.com/CatchZeng/feishu/pkg/feishu"
> ```

Got it. It works now.
